spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: a7z!56Nf
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create